name: aegis
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  latlong2: 0.9.1
  vector_math: ^2.1.0
  http: ^1.2.1
  flutter_svg: ^2.0.7
  xml: ^6.1.0
  path_drawing: ^1.0.1
  provider: ^6.0.5

  google_maps_flutter: ^2.13.1
  flutter_map_heatmap: ^0.0.8
  flutter_map: ^7.0.2  # Downgraded to be compatible with flutter_map_heatmap
  shared_preferences: ^2.2.2
  flutter_riverpod: ^3.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 

flutter:
  uses-material-design: true
  
  # Assets should be placed here, not under dependencies
  assets:
    - assets/images/logo.png
    - assets/images/chicago_communities.svg